menu:
  Home: /
  Archives: /archives
rss: /atom.xml

archive_date_format: YYYY MMM DD
fancybox: true

widgets:
- category
- tagcloud
- recent_posts

widgets_pos_right: 

share:
  enable: false
  qq: false

gotop:
  enable: true
  soll_top: 350
  speed: 800

duoshuo_shortname: lyhopq

google_analytics:
baidu_tongji: true
favicon: /favicon.ico
