menu:
  首页: /
  归档: /archives
  关于: /about

excerpt_link: 阅读全文
archive_yearly: false
archive_date_format: MMM DD

widgets:
  - category
#  - tag
  - tagcloud
  - recent_posts
#  - blogroll


fancybox: true

duoshuo_shortname: lyhopq

favicon: /favicon.ico
google_analytics:
rss:
